# -*- coding: utf-8 -*-
"""unlited1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A2quxlFZnFuZmJo4sEJJR9Deow-iCqy2
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df=sns.load_dataset("iris")

print(df.head(10))

print(df.tail(10))

print("Shape:",df.shape)

print("Columns:",df.columns.tolist())

print(df.dtypes)

df.info()

print(df.isnull().sum())

print("Total missing values:",df.isnull().sum().sum())

print("Number of rows:",len(df))

print("Number of columns:",df.shape[1])

print(df["species"].value_counts())

print(df["species"].value_counts(normalize=True)*100)

print("species:",df["species"].unique())

print("Number of unique species:",df["species"].nunique())

print(df.describe())

print(df.select_dtypes("number").mean())

print(df.select_dtypes("number").median())

print(df.select_dtypes("number").std())

sns.countplot(data=df,x="species")
plt.title("Number of Flowers by Species")
plt.xlabel("Species")
plt.ylabel("Count")
plt.show()

sns.histplot(
    data=df,
    x="sepal_length",
    bins=10,
    kde=True
)

sns.boxplot(
    data=df,
    x="species",
    y="petal_length"
)
plt.title("Petal Length by Species")
plt.show()





